### ISSUE TITLE
About the batchsize and num_workers

### ISSUE THREAD

**Issue by FionaZhangJ** [mecarill/classawareteacher#6]
When I was training on the 4X3090, I noticed that gpu utilization fluctuates and often goes as low as 0, so I would like to ask about the batch size settings of the author, and the setting of num workers.

**Comment by FionaZhangJ** [comment]
> When I was training on the 4X3090, I noticed that gpu utilization fluctuates and often goes as low as 0, so I would like to ask about the batch size settings of the author, and the setting of num workers.

**Comment by wdseh** [comment]
I met a similiar situation like you, how did you fix this problem?
